### ISSUE TITLE
Base64URL valid characters are not properly validated

### ISSUE THREAD

**Issue by pacu** [zecdev/zcash-swift-payment-uri#69]
reported https://github.com/Electric-Coin-Company/zashi-ios/issues/1420 here

**Comment by daira** [comment]
I have little time to work on this, but I see the problem. It's here: https://github.com/zecdev/zcash-swift-payment-uri/blob/75ca8f38b2de6f6cedf1c52744df69d07d2d2496/Sources/ZcashPaymentURI/Model.swift#L110-L111

This converts the base64url string into a base64 string just by substituting `/` in place of `_` and `+` in place of `-`. This doesn't detect cases where the string already contained `/` or `+`, or contains `=` (which ZIP 321 also prohibits).
